import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { WebSocket } from 'ws';
const browser=await chromium.launch();
let guest;
let latest;
try {
  const page=await browser.newPage({viewport:{width:1440,height:1000}});
  const errors=[];
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto(process.env.TEST_URL || 'http://127.0.0.1:3000');
  await page.evaluate(async()=> {
    const {InputController}=await import('/js/input.js');
    const canvas=document.createElement('canvas');
    canvas.id='input-test';
    canvas.width=300;
    canvas.height=100;
    document.body.prepend(canvas);
    window.probe=new InputController(canvas);
    window.probe.active=true;
  });
  const read=()=>page.evaluate(()=>window.probe.read({x:100,y:50,alive:true}));
  await page.locator('#input-test').click();
  const short=await read();
  assert.equal(short.throw,true);
  assert.ok(short.range<200);
  await page.locator('#input-test').hover();
  await page.mouse.down();
  await page.waitForTimeout(1000);
  assert.equal((await read()).throw,false);
  await page.mouse.up();
  assert.equal((await read()).range,630);
  assert.equal((await read()).throw,false);
  await page.keyboard.press('KeyF');
  assert.equal((await read()).strike,true);
  await page.locator('#input-test').click({button:'right'});
  assert.equal((await read()).strike,true);
  await page.mouse.down();
  await page.evaluate(()=>window.dispatchEvent(new Event('blur')));
  await page.mouse.up();
  assert.equal((await read()).throw,false);
  await page.evaluate(()=>window.dispatchEvent(new Event('focus')));
  await page.evaluate(()=>{window.probe.active=false;document.querySelector('#input-test').remove();});
  await page.locator('#create-button').click();
  await page.locator('#room-screen').waitFor({state:'visible'});
  const code=(await page.locator('#copy-code').textContent()).trim().split(' ')[0];
  guest=new WebSocket((process.env.TEST_URL || 'http://127.0.0.1:3000').replace('http','ws')+'/ws');
  guest.on('message',raw=>{const message=JSON.parse(raw);if(message.type==='state') latest=message.state;});
  await new Promise(resolve=>guest.once('open',resolve));
  guest.send(JSON.stringify({type:'join',code,name:'Stationary rival'}));
  await page.waitForFunction(()=>!document.querySelector('#start-button').disabled);
  await page.locator('#start-button').click();
  await page.locator('#game-screen').waitFor({state:'visible'});
  await page.waitForTimeout(3400);
  await page.locator('#game').hover({position:{x:300,y:130}});
  await page.mouse.down();
  await page.waitForTimeout(500);
  await page.screenshot({path:'artifacts/charged-throw.png',fullPage:true});
  await page.mouse.up();
  await page.keyboard.press('KeyF');
  await page.waitForTimeout(100);
  assert.notEqual(await page.locator('#strike-ready').textContent(),'READY');
  assert.ok(latest.players[0].strikeCooldown>0,'Remote client receives the strike');
  await page.screenshot({path:'artifacts/strike.png',fullPage:true});
  assert.deepEqual(errors,[]);
  console.log('Attack browser checks passed: tap/hold/release, F/right-click, blur cancellation, charge preview, strike cooldown.');
} finally {guest?.terminate();await browser.close();}
