import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';

const base=process.env.TEST_URL || 'http://127.0.0.1:3000';
const browser=await chromium.launch({headless:true});
const errors=[];
async function page(width=1440,height=900) {
  const context=await browser.newContext({viewport:{width,height}});
  const page=await context.newPage();
  page.on('pageerror',error=>errors.push(error.message));
  await page.goto(base);
  return page;
}
await mkdir('artifacts',{recursive:true});
try {
  const host=await page();
  await host.screenshot({path:'artifacts/lobby-desktop.png',fullPage:true});
  await host.getByRole('button',{name:'Choose Watermelon',exact:true}).click();
  assert.equal(await host.locator('#character-name').textContent(),'Watermelon');
  await host.locator('#how-button').click();
  assert.equal(await host.locator('#help-dialog').evaluate(node=>node.open),true);
  await host.locator('#close-help').click();
  await host.locator('#practice-button').click();
  await host.locator('#game-screen').waitFor({state:'visible'});
  await host.waitForTimeout(3400);
  await host.keyboard.down('KeyD');
  await host.waitForTimeout(250);
  await host.keyboard.up('KeyD');
  await host.locator('#game').click({position:{x:600,y:240}});
  await host.keyboard.press('Space');
  await host.screenshot({path:'artifacts/practice.png',fullPage:true});
  assert.equal(await host.locator('.score-pill').count(),4);
  await host.locator('#leave-game').click();
  await host.locator('#player-name').fill('Host <test>');
  await host.locator('#create-button').click();
  await host.locator('#room-screen').waitFor({state:'visible'});
  const code=(await host.locator('#copy-code').textContent()).trim().split(' ')[0];
  assert.match(code,/^[A-Z2-9]{5}$/);
  assert.equal(await host.locator('#start-button').isDisabled(),true);
  const guest=await page();
  await guest.locator('#player-name').fill('Garden Guest');
  await guest.locator('#room-code').fill(code);
  await guest.locator('#join-button').click();
  await guest.locator('#room-screen').waitFor({state:'visible'});
  await host.waitForFunction(()=>document.querySelectorAll('.room-player').length===2);
  assert.equal(await guest.locator('#start-button').isDisabled(),true);
  assert.ok((await guest.locator('#room-players').textContent()).includes('Host <test>'));
  await host.screenshot({path:'artifacts/private-room.png',fullPage:true});
  await host.locator('#start-button').click();
  await host.locator('#game-screen').waitFor({state:'visible'});
  await guest.locator('#game-screen').waitFor({state:'visible'});
  await host.waitForTimeout(3400);
  assert.equal(await host.locator('.score-pill').count(),2);
  assert.equal(await guest.locator('.score-pill').count(),2);
  await host.keyboard.down('KeyD');
  await host.waitForTimeout(250);
  await host.keyboard.up('KeyD');
  await host.screenshot({path:'artifacts/multiplayer.png',fullPage:true});
  await guest.locator('#leave-game').click();
  await host.locator('#room-screen').waitFor({state:'visible'});
  assert.equal(await host.locator('.room-player').count(),1);
  const mobile=await page(390,844);
  await mobile.screenshot({path:'artifacts/lobby-mobile.png',fullPage:true});
  assert.equal(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),true);
  const missing=await fetch(`${base}/server/index.js`);
  assert.equal(missing.status,404);
  assert.deepEqual(errors,[]);
  console.log('Browser checks passed: character selection, help, practice, 2-client rooms/match, disconnect recovery, mobile layout, no JS errors.');
} finally { await browser.close(); }
